<?php

namespace GrowupFrontendBundle\Repository;

/**
 * IdeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdeaRepository extends \Doctrine\ORM\EntityRepository
{
    const ALIAS ="idea";


    public function fetchIdeas($id){
        $queryBuilder = $this->getEntityManager()
            ->createQuery('SELECT i FROM GrowupFrontendBundle:Idea i WHERE i.candidate =:id')
            ->setParameter('id', $id);
        return $queryBuilder->execute();

}
}


